name: Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build an Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and Push Docker Image
        run: |
          VERSION=$(date +%s)
          docker login docker.pkg.github.com --username macielti --password ${{ secrets.GITHUB_TOKEN }}
          docker build . --tag docker.pkg.github.com/macielti/porteiro/porteiro:latest
          docker push docker.pkg.github.com/macielti/porteiro/porteiro:latest
        env:
          CI: true
